[package]
name = "blog_os"
version = "0.1.0"
authors = ["Yosef Deray <yosefderay770@gmail.com>"]

[dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[package.metadata.bootimage]
default-target = "x86_64-blog_os.json"
